---
- name: Загрузка Zabbix репозитория
  shell: wget https://repo.zabbix.com/zabbix/7.2/release/debian/pool/main/z/zabbix-release/zabbix-release_latest_7.2+debian12_all.deb
  args:
    chdir: /tmp

- name: Установка Zabbix репозитория
  shell: dpkg -i zabbix-release_latest_7.2+debian12_all.deb
  args:
    chdir: /tmp

- name: Обновление пакетов
  apt:
    update_cache: yes

- name: Установка дополнительных пакетов для Zabbix
  apt:
    name:
    - zabbix-web-service
    - postgresql
    - postgresql-contrib
    - python3-pexpect
    - python3-pip
    - python3-dev
    - python3-venv
    - python3-psycopg2
    - zabbix-server-pgsql
    - zabbix-frontend-php
    - php8.2-pgsql
    - zabbix-apache-conf
    - zabbix-sql-scripts
    - zabbix-agent
    state: present

- name: Создание пользователя в postgresql
  ansible.builtin.expect:
    command: sudo -u postgres createuser --pwprompt zabbix
    responses:
      (?i).*(Enter password for new role)(.*):
       - '{{ password_db }}'
      (?i).*(Enter it again)(.*):
       - '{{ password_db }}'
- name: Создание базы в postgresql
  shell: sudo -u postgres createdb -O zabbix zabbix

- name: Импорт схемы
  shell: zcat /usr/share/zabbix/sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix

- name: Настройка DBPassword в конфигурационном файле Zabbix
  lineinfile:
    path: /etc/zabbix/zabbix_server.conf
    regexp: '^DBPassword='
    line: 'DBPassword={{ password_db }}'

- name: Перезагрузка zabbix-server service
  ansible.builtin.systemd:
    name: zabbix-server
    state: restarted
    enabled: true

- name: Перезагрузка zabbix-agent service
  ansible.builtin.systemd:
    name: zabbix-agent
    state: restarted
    enabled: true

- name: Перезагрузка apache2 service
  ansible.builtin.systemd:
    name: apache2
    state: restarted
    enabled: true

- name: Перезагрузка Zabbix WEB
  ansible.builtin.systemd:
    name: zabbix-web-service
    state: restarted
    enabled: true