---
- name: Загрузка Filebeat репозитория
  shell: wget https://mirror.yandex.ru/mirrors/elastic/7/pool/main/f/filebeat/filebeat-7.17.9-amd64.deb
  args:
    chdir: /tmp

- name: Установка Filebeat репозитория
  shell: dpkg -i filebeat-7.17.9-amd64.deb
  args:
    chdir: /tmp

- name: Обновление пакетов
  apt:
    update_cache: yes

- name: Импортируем настройки
  copy: 
    src: /home/timakhova/diploma2/ansible/roles/filebeat/vars/main.yml
    dest: /etc/filebeat/filebeat.yml

- name: Перезагрузка Filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: true