---
- name: Загрузка Zabbix репозитория
  shell: wget https://repo.zabbix.com/zabbix/7.2/release/debian/pool/main/z/zabbix-release/zabbix-release_latest_7.2+debian12_all.deb
  args:
    chdir: /tmp

- name: Установка Zabbix репозитория
  shell: dpkg -i zabbix-release_latest_7.2+debian12_all.deb
  args:
    chdir: /tmp

- name: Обновление пакетов
  apt:
    update_cache: yes

- name: Установка агента для Zabbix
  apt:
    name:
    - zabbix-agent
    state: present

- name: Подключаем к нашему серверу
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: '^Server=127.0.0.1'
    line: 'Server=zabbix.ru-central1.internal'

- name: Перезагрузка Zabbix агента
  ansible.builtin.systemd:
    name: zabbix-agent
    state: restarted
    enabled: true